import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import { getCookie } from 'cookies-next';
import { useEffect, useState } from 'react';

export default function Welcome() {
  const [username, setUsername] = useState('');

  // const getusername = async () => {
  //   const access_token = getCookie('access_token');
  //   const userinfoResponse = await fetch(
  //     `${process.env.NEXT_PUBLIC_ORY_URL}/userinfo`,
  //     {
  //       method: 'GET',
  //       headers: { Authorization: 'Bearer ' + access_token },
  //     },
  //   );
  //   const data = await userinfoResponse.json();
  //   setUsername(data.sub);
  // };

  useEffect(() => {
    // getusername();
    const name = getCookie('user_name');
    if (name) {
      setUsername(name);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hi {username}, Welcome!!!!⚡</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
